import { Alkatra, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Footer from "./common/Footer";
import MainContext from "./context/MainContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alkatra = Alkatra({
  subsets: ['latin'],
  variable: '--font-alkatra', // 👈 used in Tailwind config
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${alkatra.variable} antialiased`}
      >
        <MainContext>
          <Header />
          {children}
          <Footer />
        </MainContext>
      </body>
    </html>
  );
}
